services:
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434'
#  postgres:
#    image: 'postgres:latest'
#    environment:
#      - 'POSTGRES_DB=mydatabase'
#      - 'POSTGRES_PASSWORD=secret'
#      - 'POSTGRES_USER=myuser'
#    ports:
#      - '5432'
  postgres_db:
    container_name: "postgres_db"
    image: "postgres"
    env_file: ./.env
    ports:
      - ${DB_LOCAL_PORT}:${DB_DOCKER_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:${DB_VOLUME_URL}

  chroma_db:
    container_name: "chroma_db"
    image: "ghcr.io/chroma-core/chroma:0.5.4"
    env_file: ./.env
    ports:
      - ${CHROMA_LOCAL_PORT}:${CHROMA_DOCKER_PORT}

volumes:
  postgres-data: